<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Andrey Kolesnichenko</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <AssemblyVersion>0.2.0</AssemblyVersion>
    <FileVersion>0.2.0</FileVersion>
    <Version>0.2.0</Version>
    <Copyright>Copyright 2026 Andrey Kolesnichenko</Copyright>
    <PackageTags>Retry Delay</PackageTags>
    <PackageIcon>RetryDelays.png</PackageIcon>
    <PackageReadmeFile>NuGet.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/kolan72/RetryDelays</PackageProjectUrl>
    <RepositoryUrl>https://github.com/kolan72/RetryDelays</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\RetryDelays.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="docs\NuGet.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
